### ISSUE TITLE
Missing Pokemon

### ISSUE THREAD

**Issue by fOmey** [PokemonGOAPI/PokemonDataGraber#3]
I have noticed a few Pokemon are missing from the output file.. If you do a ctrl + f and search: "{}," you will be able to locate them all.

**Comment by BrunnerLivio** [comment]
Alright. Thanks for reporting! Found out Pokemon Ho Oh, Pidgeot and some more are missing. Trying to find a pattern why it fails.

**Comment by BrunnerLivio** [comment]
Seems like this issue is not relevant anymore, because the whole tool does not work anymore haha.

See issue #4
